Attribute VB_Name = "Progress_bars"
' Global variable declaration
Public colorTotalBar As Long
Public colorProgressBar As Long
Public totalBarBorderColor As Long
Public barBorderThickness As Single
Public barWidth As Single
Public totalBarLength As Single
Public progressBarLength As Single
Public barHeight As Single
Public barYPosition As Single
Public excludeFirst As Boolean
Public excludeLast As Boolean

Sub InitializeVariables_Bar()
    ' Initialize global variables for the progress bars
    colorTotalBar = RGB(202, 202, 202) ' Color for the total slides bar (light gray)
    totalBarBorderColor = RGB(0, 0, 0) ' Border color for the total bar (black)
    barBorderThickness = 0.75 ' Thickness of the total bar border in points
    
    colorProgressBar = RGB(0, 0, 0) ' Color for the progress bar (green)
    
    barWidth = 10 ' Width of both bars
    totalBarLength = 500 ' Length of the total bar
    barHeight = ActivePresentation.PageSetup.SlideHeight - 100 ' Vertical position of the bars
    barYPosition = ActivePresentation.PageSetup.SlideHeight - 50 ' Adjustable Y position for the bars
    
    ' Variables for excluding the first or last slide
    excludeFirst = False
    excludeLast = False
End Sub

Sub DrawProgressBars()
    Dim sld As Slide
    Dim totalSlides As Integer
    Dim currentSlide As Integer
    Dim xPos As Single
    Dim yPos As Single
    Dim progressBarLength As Single
    Dim i As Integer

    ' Ensure variables are initialized
    Call InitializeVariables_Bar

    totalSlides = ActivePresentation.Slides.Count
    
    ' Adjust total slides if excluding the first or last
    If excludeFirst Then totalSlides = totalSlides - 1
    If excludeLast Then totalSlides = totalSlides - 1

    ' Calculate the initial X position for the bar
    xPos = (ActivePresentation.PageSetup.SlideWidth - totalBarLength) / 2
    yPos = barYPosition ' Adjustable Y position

    ' Clear previous bars
    Call ClearBars_AllSlides

    ' Draw bars on all slides
    For Each sld In ActivePresentation.Slides
        currentSlide = sld.SlideIndex
        
        ' Skip the first or last slide if excluded
        If excludeFirst And currentSlide = 1 Then GoTo NextSlide
        If excludeLast And currentSlide = ActivePresentation.Slides.Count Then GoTo NextSlide

        ' Draw the total bar (Bar1)
        With sld.Shapes.AddShape(msoShapeRectangle, xPos, yPos, totalBarLength, barWidth)
            .Fill.ForeColor.RGB = colorTotalBar
            .Line.ForeColor.RGB = totalBarBorderColor
            .Line.Weight = barBorderThickness ' Border thickness in points
            .Name = "TotalBar"
        End With

        ' Calculate the length of the progress bar based on the number of slides completed
        progressBarLength = (currentSlide / totalSlides) * totalBarLength

        ' Draw the progress bar (Bar2)
        With sld.Shapes.AddShape(msoShapeRectangle, xPos, yPos, progressBarLength, barWidth)
            .Fill.ForeColor.RGB = colorProgressBar
            .Line.Visible = msoFalse ' No border for the progress bar
            .Name = "ProgressBar"
        End With

NextSlide:
    Next sld
End Sub

Sub ClearBars_AllSlides()
    Dim sld As Slide
    Dim shp As Shape
    ' Clear previous bars generated by this macro on all slides
    For Each sld In ActivePresentation.Slides
        For i = sld.Shapes.Count To 1 Step -1
            Set shp = sld.Shapes(i)
            If shp.Name = "TotalBar" Or shp.Name = "ProgressBar" Then
                shp.Delete
            End If
        Next i
    Next sld
End Sub

Sub ClearBars_CurrentSlide()
    ' Remove bars from the current slide
    Dim sld As Slide
    Dim shp As Shape
    Set sld = ActiveWindow.View.Slide

    For i = sld.Shapes.Count To 1 Step -1
        Set shp = sld.Shapes(i)
        If shp.Name = "TotalBar" Or shp.Name = "ProgressBar" Then
            shp.Delete
        End If
    Next i
End Sub

